In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [ ]:
print(os.path.exists(CELEB_ROOT))
print(os.path.exists(FF_ROOT))

In [ ]:
import os

print(os.path.exists(CELEB_ROOT))
print(os.path.exists(FF_ROOT))

In [ ]:
import os

CELEB_ROOT = "/content/Celeb-DF"
FF_ROOT = "/content/FaceForensics++"

print("Celeb-DF:", os.path.exists(CELEB_ROOT))
print("FaceForensics++:", os.path.exists(FF_ROOT))

In [ ]:
import os

print(os.listdir("/content"))

In [ ]:
import os

print(os.listdir('/kaggle/input'))

In [ ]:
import os

print(os.listdir('/kaggle/input/datasets'))

In [ ]:
import os

for folder in ['reubensuju', 'xdxd003']:
    path = f'/kaggle/input/datasets/{folder}'
    print("\n==========", folder, "==========")
    print(os.listdir(path))

In [ ]:
import os

CELEB_ROOT = "/kaggle/input/datasets/reubensuju/celeb-df-v2"
FF_ROOT = "/kaggle/input/datasets/xdxd003/ff-c23"

print("Celeb-DF exists:", os.path.exists(CELEB_ROOT))
print("FaceForensics++ exists:", os.path.exists(FF_ROOT))

In [ ]:
print("Celeb-DF contents:")
print(os.listdir(CELEB_ROOT))

print("\nFaceForensics++ contents:")
print(os.listdir(FF_ROOT))

In [ ]:
import os

CELEB_ROOT = "/kaggle/input/datasets/reubensuju/celeb-df-v2"
FF_ROOT = "/kaggle/input/datasets/xdxd003/ff-c23/FaceForensics++_C23"

print("Celeb-DF exists:", os.path.exists(CELEB_ROOT))
print("FF++ exists:", os.path.exists(FF_ROOT))

In [ ]:
print(os.listdir(FF_ROOT))

In [ ]:
print("Celeb-real:")
print(os.listdir(os.path.join(CELEB_ROOT, "Celeb-real"))[:5])

print("\nCeleb-synthesis:")
print(os.listdir(os.path.join(CELEB_ROOT, "Celeb-synthesis"))[:5])

print("\nFF++ Original:")
print(os.listdir(os.path.join(FF_ROOT, "original"))[:5])

print("\nFF++ Deepfakes:")
print(os.listdir(os.path.join(FF_ROOT, "Deepfakes"))[:5])

In [ ]:
import os
import torch
import torchvision
import numpy as np
import pandas as pd

print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("NumPy:", np.__version__)

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import os
import pandas as pd

STEP4_DIR = "/kaggle/working/step4_faces"

METADATA_PATH = os.path.join(
    STEP4_DIR,
    "step4_test_metadata.csv"
)

print("Step 4 directory exists:",
      os.path.exists(STEP4_DIR))

print("Metadata exists:",
      os.path.exists(METADATA_PATH))

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import torch
import torchvision
import PIL
import numpy

print("Torch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("Pillow:", PIL.__version__)
print("NumPy:", numpy.__version__)

In [ ]:
from facenet_pytorch import MTCNN

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

mtcnn = MTCNN(
    keep_all=True,
    device=device
)

print("MTCNN loaded successfully")

In [ ]:
!pip install facenet-pytorch==2.6.0

In [ ]:
import torch
import torchvision
import numpy as np
import pandas as pd

print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("NumPy:", np.__version__)
print("CUDA:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import os
import cv2
import pandas as pd
import numpy as np

from PIL import Image
from tqdm.auto import tqdm

import torch
from facenet_pytorch import MTCNN

In [ ]:
!pip install -q --no-cache-dir facenet-pytorch==2.6.0

In [ ]:
import requests

r = requests.get("https://pypi.org", timeout=10)
print(r.status_code)

In [ ]:
import socket

try:
    print(socket.gethostbyname("pypi.org"))
    print("Internet/DNS is working")
except Exception as e:
    print("DNS is NOT working:", e)

In [ ]:
!pip install facenet-pytorch==2.6.0

In [ ]:
import torch
import torchvision
import facenet_pytorch

print("Torch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("FaceNet-PyTorch:", facenet_pytorch.__version__)
print("CUDA:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import PIL

print("Pillow version:", PIL.__version__)
print("Pillow location:", PIL.__file__)

In [ ]:
!pip install -q facenet-pytorch==2.6.0

In [ ]:
import facenet_pytorch

print("FaceNet-PyTorch:", facenet_pytorch.__version__)

In [ ]:
!pip install -q --force-reinstall "Pillow==10.2.0"

In [ ]:
import PIL
print("Pillow:", PIL.__version__)

In [ ]:
!pip install --force-reinstall --no-cache-dir "Pillow==10.2.0"

In [ ]:
import PIL
print("Pillow:", PIL.__version__)

In [ ]:
import torch
import torchvision

print("Torch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("CUDA:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
from facenet_pytorch import MTCNN

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

mtcnn = MTCNN(
    keep_all=True,
    device=device
)

print("✅ MTCNN loaded successfully")

In [ ]:
import os
import cv2
import torch
import pandas as pd
import numpy as np

from PIL import Image
from tqdm.auto import tqdm
from facenet_pytorch import MTCNN

print("Imports successful")

In [ ]:
CELEB_ROOT = "/kaggle/input/datasets/reubensuju/celeb-df-v2"
FF_ROOT = "/kaggle/input/datasets/xdxd003/ff-c23"

OUTPUT_DIR = "/kaggle/working/step4_faces"
FACES_DIR = os.path.join(OUTPUT_DIR, "faces")

os.makedirs(FACES_DIR, exist_ok=True)

print("Celeb-DF exists:", os.path.exists(CELEB_ROOT))
print("FF++ exists:", os.path.exists(FF_ROOT))

In [ ]:
def get_kaggle_video_path(relative_path):

    path = relative_path.replace("\\", "/")

    # Celeb-DF
    if "data/raw/cel/" in path:

        relative = path.split(
            "data/raw/cel/",
            1
        )[1]

        return os.path.join(
            CELEB_ROOT,
            relative
        )

    # FaceForensics++
    elif "data/raw/FaceForensics++_C23/" in path:

        relative = path.split(
            "data/raw/FaceForensics++_C23/",
            1
        )[1]

        return os.path.join(
            FF_ROOT,
            relative
        )

    return None

print("✅ Path conversion function ready")

In [ ]:
CSV_PATH = "/kaggle/working/clean_video_list.csv"

df = pd.read_csv(CSV_PATH)

print("Total videos:", len(df))
print("Columns:", df.columns.tolist())
display(df.head())

In [ ]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file == "clean_video_list.csv":
            print("FOUND:", os.path.join(root, file))

In [ ]:
import pandas as pd

CSV_URL = "https://raw.githubusercontent.com/NancyKashyap29/deepfake-detector-project/refs/heads/master/logs/clean_video_list.csv"

df = pd.read_csv(CSV_URL)

print("Total videos:", len(df))
print("Columns:", df.columns.tolist())

display(df.head(10))

In [ ]:
df.to_csv(
    "/kaggle/working/clean_video_list.csv",
    index=False
)

print("✅ CSV saved locally")

In [ ]:
import os

print(
    os.path.exists(
        "/kaggle/working/clean_video_list.csv"
    )
)

In [ ]:
import os

CELEB_ROOT = "/kaggle/input/datasets/reubensuju/celeb-df-v2"
FF_ROOT = "/kaggle/input/datasets/xdxd003/ff-c23"

OUTPUT_DIR = "/kaggle/working/step4_faces"
FACES_DIR = os.path.join(OUTPUT_DIR, "faces")

os.makedirs(FACES_DIR, exist_ok=True)

print("Celeb-DF exists:", os.path.exists(CELEB_ROOT))
print("FF++ exists:", os.path.exists(FF_ROOT))

In [ ]:
def get_kaggle_video_path(relative_path):

    path = relative_path.replace("\\", "/")

    if "data/raw/cel/" in path:

        relative = path.split(
            "data/raw/cel/",
            1
        )[1]

        return os.path.join(
            CELEB_ROOT,
            relative
        )

    elif "data/raw/FaceForensics++_C23/" in path:

        relative = path.split(
            "data/raw/FaceForensics++_C23/",
            1
        )[1]

        return os.path.join(
            FF_ROOT,
            relative
        )

    return None

print("✅ Path conversion ready")

In [ ]:
import torch
from facenet_pytorch import MTCNN

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

mtcnn = MTCNN(
    keep_all=True,
    device=device
)

print("✅ MTCNN loaded successfully")

In [ ]:
import cv2
import pandas as pd
import numpy as np
from PIL import Image
from tqdm.auto import tqdm
import os

# -----------------------------
# Settings for TEST
# -----------------------------

NUM_TEST_VIDEOS = 10

# Process every 10th frame
FRAME_INTERVAL = 10

# Minimum face confidence
MIN_CONFIDENCE = 0.90

results = []

# Take first 10 videos
test_df = df.head(NUM_TEST_VIDEOS)

print("Videos to test:", len(test_df))
print("=" * 60)


# -----------------------------
# Process videos
# -----------------------------

for video_index, row in tqdm(
    test_df.iterrows(),
    total=len(test_df),
    desc="Step 4 test"
):

    csv_path = row["video_path"]

    # Convert CSV path → Kaggle dataset path
    video_path = get_kaggle_video_path(csv_path)

    if video_path is None or not os.path.exists(video_path):
        print("❌ Missing:", csv_path)
        continue

    # Open video
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("❌ Could not open:", video_path)
        continue

    frame_number = 0
    frames_checked = 0
    faces_found = 0

    # -----------------------------
    # Read frames
    # -----------------------------

    while True:

        ret, frame = cap.read()

        if not ret:
            break

        # Only process every 10th frame
        if frame_number % FRAME_INTERVAL != 0:
            frame_number += 1
            continue

        frames_checked += 1

        # BGR → RGB
        rgb_frame = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2RGB
        )

        # Convert to PIL image
        image = Image.fromarray(rgb_frame)

        # -----------------------------
        # Detect faces using MTCNN
        # -----------------------------

        boxes, probabilities = mtcnn.detect(image)

        if boxes is None or probabilities is None:
            frame_number += 1
            continue

        # -----------------------------
        # Keep confident faces
        # -----------------------------

        valid_faces = []

        for box, confidence in zip(
            boxes,
            probabilities
        ):

            if confidence is None:
                continue

            if confidence < MIN_CONFIDENCE:
                continue

            x1, y1, x2, y2 = box

            width = max(0, x2 - x1)
            height = max(0, y2 - y1)

            area = width * height

            valid_faces.append(
                (area, box, confidence)
            )

        if not valid_faces:
            frame_number += 1
            continue

        # -----------------------------
        # Select largest face
        # -----------------------------

        valid_faces.sort(
            key=lambda x: x[0],
            reverse=True
        )

        area, box, confidence = valid_faces[0]

        x1, y1, x2, y2 = box

        # Frame dimensions
        h, w = rgb_frame.shape[:2]

        # Make coordinates valid
        x1 = max(0, int(x1))
        y1 = max(0, int(y1))
        x2 = min(w, int(x2))
        y2 = min(h, int(y2))

        if x2 <= x1 or y2 <= y1:
            frame_number += 1
            continue

        # -----------------------------
        # Crop face
        # -----------------------------

        face = rgb_frame[y1:y2, x1:x2]

        if face.size == 0:
            frame_number += 1
            continue

        # -----------------------------
        # Create output folder
        # -----------------------------

        video_name = os.path.splitext(
            os.path.basename(csv_path)
        )[0]

        video_output_dir = os.path.join(
            FACES_DIR,
            video_name
        )

        os.makedirs(
            video_output_dir,
            exist_ok=True
        )

        # -----------------------------
        # Save face image
        # -----------------------------

        face_filename = (
            f"frame_{frame_number:06d}.jpg"
        )

        face_path = os.path.join(
            video_output_dir,
            face_filename
        )

        Image.fromarray(face).save(
            face_path,
            quality=95
        )

        faces_found += 1

        # -----------------------------
        # Save metadata
        # -----------------------------

        results.append({
            "video_path": csv_path,
            "frame_number": frame_number,
            "face_path": face_path,
            "confidence": float(confidence),
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "face_width": x2 - x1,
            "face_height": y2 - y1
        })

        frame_number += 1

    cap.release()

    print(
        f"{video_index + 1}/{len(test_df)} | "
        f"frames checked: {frames_checked} | "
        f"faces saved: {faces_found}"
    )


# -----------------------------
# Save metadata
# -----------------------------

results_df = pd.DataFrame(results)

metadata_path = os.path.join(
    OUTPUT_DIR,
    "step4_test_metadata.csv"
)

results_df.to_csv(
    metadata_path,
    index=False
)


# -----------------------------
# Final report
# -----------------------------

print("\n" + "=" * 60)
print("✅ STEP 4 TEST COMPLETE")
print("=" * 60)

print("Videos tested:", len(test_df))
print("Face crops saved:", len(results_df))
print("Metadata file:", metadata_path)

if len(results_df) > 0:

    print(
        "Average confidence:",
        round(
            results_df["confidence"].mean(),
            4
        )
    )

    print("\nFirst 5 results:")
    display(results_df.head())

In [ ]:
import os
import pandas as pd

METADATA_PATH = "/kaggle/working/step4_faces/step4_test_metadata.csv"

print("Metadata exists:", os.path.exists(METADATA_PATH))

results_df = pd.read_csv(METADATA_PATH)

print("Total face crops:", len(results_df))
print("Columns:")
print(results_df.columns.tolist())

display(results_df.head())

In [ ]:
def get_dataset_name(video_path):
    
    if "data/raw\\cel\\" in video_path or "data/raw/cel/" in video_path:
        return "Celeb-DF"
    
    elif "FaceForensics++_C23" in video_path:
        return "FaceForensics++"
    
    return "Unknown"


results_df["dataset"] = results_df["video_path"].apply(
    get_dataset_name
)

print(results_df["dataset"].value_counts())

In [ ]:
def get_label(video_path):

    path = video_path.replace("\\", "/").lower()

    # Celeb-DF
    if "celeb-real/" in path:
        return 0

    if "celeb-synthesis/" in path:
        return 1

    if "youtube-real/" in path:
        return 0

    # FaceForensics++
    if "/original/" in path:
        return 0

    return 1


results_df["label"] = results_df["video_path"].apply(
    get_label
)

results_df["label_name"] = results_df["label"].map({
    0: "REAL",
    1: "FAKE"
})

print(results_df["label_name"].value_counts())

display(
    results_df[
        ["video_path", "face_path", "label", "label_name"]
    ].head()
)

In [ ]:
print("REAL:", (results_df["label"] == 0).sum())
print("FAKE:", (results_df["label"] == 1).sum())

In [ ]:
# Normalize paths
df["normalized_path"] = df["video_path"].str.replace("\\", "/", regex=False)

# Create video-level labels
def get_video_label(path):
    path = path.lower()

    # REAL
    if "celeb-real/" in path:
        return 0
    elif "youtube-real/" in path:
        return 0
    elif "/original/" in path:
        return 0

    # FAKE
    elif "celeb-synthesis/" in path:
        return 1
    else:
        return 1


df["label"] = df["normalized_path"].apply(get_video_label)

df["label_name"] = df["label"].map({
    0: "REAL",
    1: "FAKE"
})

print("Video-level distribution:")
print(df["label_name"].value_counts())

In [ ]:
NUM_REAL = 5
NUM_FAKE = 5

real_videos = df[df["label"] == 0].head(NUM_REAL)
fake_videos = df[df["label"] == 1].head(NUM_FAKE)

test_videos = pd.concat(
    [real_videos, fake_videos]
).sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Test videos:", len(test_videos))
print("\nClass distribution:")
print(test_videos["label_name"].value_counts())

display(
    test_videos[
        ["video_path", "label", "label_name"]
    ]
)

In [ ]:
test_df = test_videos

In [ ]:
results.append({
    "video_path": csv_path,
    "frame_number": frame_number,
    "face_path": face_path,
    "confidence": float(confidence),
    "x1": x1,
    "y1": y1,
    "x2": x2,
    "y2": y2,
    "face_width": x2 - x1,
    "face_height": y2 - y1,
    "label": int(row["label"]),
    "label_name": row["label_name"]
})

In [ ]:
# Recreate labels in the main dataframe

df["normalized_path"] = df["video_path"].str.replace(
    "\\", "/", regex=False
)

def get_video_label(path):
    path = path.lower()

    # REAL
    if "celeb-real/" in path:
        return 0
    elif "youtube-real/" in path:
        return 0
    elif "/original/" in path:
        return 0

    # FAKE
    elif "celeb-synthesis/" in path:
        return 1
    else:
        return 1


df["label"] = df["normalized_path"].apply(get_video_label)

df["label_name"] = df["label"].map({
    0: "REAL",
    1: "FAKE"
})

print(df["label_name"].value_counts())

In [ ]:
NUM_REAL = 5
NUM_FAKE = 5

real_videos = df[df["label"] == 0].head(NUM_REAL)
fake_videos = df[df["label"] == 1].head(NUM_FAKE)

test_videos = pd.concat(
    [real_videos, fake_videos]
).sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Videos selected:", len(test_videos))
print("\nClass distribution:")
print(test_videos["label_name"].value_counts())

display(
    test_videos[
        ["video_path", "label", "label_name"]
    ]
)

In [ ]:
test_df = test_videos.copy()

print("test_df columns:")
print(test_df.columns.tolist())

print("\nLabels:")
print(test_df["label_name"].value_counts())

In [ ]:
test_df = test_videos

In [ ]:
results.append({
    "video_path": csv_path,
    "frame_number": frame_number,
    "face_path": face_path,
    "confidence": float(confidence),
    "x1": x1,
    "y1": y1,
    "x2": x2,
    "y2": y2,
    "face_width": x2 - x1,
    "face_height": y2 - y1,
    "label": int(row["label"]),
    "label_name": row["label_name"]
})

In [ ]:
# Make sure labels exist in df

df["normalized_path"] = df["video_path"].str.replace(
    "\\", "/", regex=False
)

def get_video_label(path):
    path = path.lower()

    if "celeb-real/" in path:
        return 0          # REAL

    elif "youtube-real/" in path:
        return 0          # REAL

    elif "/original/" in path:
        return 0          # REAL

    elif "celeb-synthesis/" in path:
        return 1          # FAKE

    else:
        return 1          # FAKE


df["label"] = df["normalized_path"].apply(get_video_label)

df["label_name"] = df["label"].map({
    0: "REAL",
    1: "FAKE"
})

print(df["label_name"].value_counts())

In [ ]:
real_videos = df[df["label"] == 0].head(5)
fake_videos = df[df["label"] == 1].head(5)

test_videos = pd.concat(
    [real_videos, fake_videos]
).sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Videos selected:", len(test_videos))
print(test_videos["label_name"].value_counts())

display(
    test_videos[
        ["video_path", "label", "label_name"]
    ]
)

In [ ]:
import cv2
import os
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

FRAME_INTERVAL = 10
MIN_CONFIDENCE = 0.90

results = []

# IMPORTANT: use the new balanced dataset
test_df = test_videos.copy()

print("Videos to process:", len(test_df))
print("=" * 60)

for video_index, row in tqdm(
    test_df.iterrows(),
    total=len(test_df),
    desc="Step 5 face extraction"
):

    csv_path = row["video_path"]
    video_path = get_kaggle_video_path(csv_path)

    label = int(row["label"])
    label_name = row["label_name"]

    if video_path is None or not os.path.exists(video_path):
        print("❌ Missing:", csv_path)
        continue

    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("❌ Could not open:", video_path)
        continue

    frame_number = 0
    frames_checked = 0
    faces_found = 0

    while True:

        ret, frame = cap.read()

        if not ret:
            break

        if frame_number % FRAME_INTERVAL != 0:
            frame_number += 1
            continue

        frames_checked += 1

        rgb_frame = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2RGB
        )

        image = Image.fromarray(rgb_frame)

        boxes, probabilities = mtcnn.detect(image)

        if boxes is None or probabilities is None:
            frame_number += 1
            continue

        valid_faces = []

        for box, confidence in zip(
            boxes,
            probabilities
        ):

            if confidence is None:
                continue

            if confidence < MIN_CONFIDENCE:
                continue

            x1, y1, x2, y2 = box

            width = max(0, x2 - x1)
            height = max(0, y2 - y1)

            area = width * height

            valid_faces.append(
                (area, box, confidence)
            )

        if not valid_faces:
            frame_number += 1
            continue

        # Largest face
        valid_faces.sort(
            key=lambda x: x[0],
            reverse=True
        )

        area, box, confidence = valid_faces[0]

        x1, y1, x2, y2 = box

        h, w = rgb_frame.shape[:2]

        x1 = max(0, int(x1))
        y1 = max(0, int(y1))
        x2 = min(w, int(x2))
        y2 = min(h, int(y2))

        if x2 <= x1 or y2 <= y1:
            frame_number += 1
            continue

        face = rgb_frame[y1:y2, x1:x2]

        if face.size == 0:
            frame_number += 1
            continue

        # Create a unique folder using label + video name
        video_name = os.path.splitext(
            os.path.basename(csv_path)
        )[0]

        video_output_dir = os.path.join(
            FACES_DIR,
            label_name,
            video_name
        )

        os.makedirs(
            video_output_dir,
            exist_ok=True
        )

        face_filename = (
            f"frame_{frame_number:06d}.jpg"
        )

        face_path = os.path.join(
            video_output_dir,
            face_filename
        )

        Image.fromarray(face).save(
            face_path,
            quality=95
        )

        faces_found += 1

        results.append({
            "video_path": csv_path,
            "frame_number": frame_number,
            "face_path": face_path,
            "confidence": float(confidence),
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
            "face_width": x2 - x1,
            "face_height": y2 - y1,
            "label": label,
            "label_name": label_name
        })

        frame_number += 1

    cap.release()

    print(
        f"{video_index + 1}/{len(test_df)} | "
        f"{label_name} | "
        f"frames checked: {frames_checked} | "
        f"faces saved: {faces_found}"
    )


# Save metadata
results_df = pd.DataFrame(results)

metadata_path = os.path.join(
    OUTPUT_DIR,
    "step5_test_metadata.csv"
)

results_df.to_csv(
    metadata_path,
    index=False
)

print("\n" + "=" * 60)
print("✅ BALANCED FACE EXTRACTION COMPLETE")
print("=" * 60)

print("Videos processed:", len(test_df))
print("Face crops saved:", len(results_df))
print("Metadata:", metadata_path)

print("\nFace crops by class:")
print(results_df["label_name"].value_counts())

In [ ]:
import os
import pandas as pd

METADATA_PATH = "/kaggle/working/step4_faces/step5_test_metadata.csv"

print("Metadata exists:",
      os.path.exists(METADATA_PATH))

results_df = pd.read_csv(METADATA_PATH)

print("Total face crops:", len(results_df))

print("\nClass distribution:")
print(results_df["label_name"].value_counts())

print("\nLabel distribution:")
print(results_df["label"].value_counts())

display(
    results_df[
        [
            "video_path",
            "face_path",
            "label",
            "label_name",
            "confidence"
        ]
    ].head(10)
)

In [ ]:
missing = 0

for path in results_df["face_path"]:
    if not os.path.exists(path):
        missing += 1

print("Total face crops:", len(results_df))
print("Missing face files:", missing)

if missing == 0:
    print("✅ All face crop files exist")
else:
    print("❌ Some face files are missing")

In [ ]:
from PIL import Image

sample_paths = results_df["face_path"].head(10)

for path in sample_paths:
    img = Image.open(path)

    print(
        os.path.basename(path),
        "→",
        img.size,
        img.mode
    )

In [ ]:
import matplotlib.pyplot as plt

sample = results_df.sample(
    min(8, len(results_df)),
    random_state=42
)

for _, row in sample.iterrows():

    img = Image.open(row["face_path"])

    plt.figure(figsize=(3, 3))
    plt.imshow(img)
    plt.title(
        f'{row["label_name"]} | '
        f'Confidence: {row["confidence"]:.4f}'
    )
    plt.axis("off")
    plt.show()

In [ ]:
import os

print("Searching for Step 4/5 metadata...\n")

for root, dirs, files in os.walk("/kaggle"):
    for file in files:
        if file.endswith(".csv") and (
            "metadata" in file.lower()
            or "clean_video" in file.lower()
            or "face" in file.lower()
        ):
            print(os.path.join(root, file))

In [ ]:
import pandas as pd

FF_METADATA = "/kaggle/input/datasets/xdxd003/ff-c23/FaceForensics++_C23/csv/FF++_Metadata.csv"

ff_df = pd.read_csv(FF_METADATA)

print("Rows:", len(ff_df))
print("Columns:")
print(ff_df.columns.tolist())

print("\nFirst 10 rows:")
display(ff_df.head(10))

In [ ]:
print("\nUnique values:")
for col in ff_df.columns:
    print(f"\n{col}:")
    print(ff_df[col].unique()[:20])

In [ ]:
print("FF++ label distribution:")
print(ff_df["Label"].value_counts())

print("\nPercentage:")
print(ff_df["Label"].value_counts(normalize=True) * 100)

In [ ]:
import os

print("Searching for CSV metadata files...")
print("=" * 70)

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.lower().endswith(".csv"):
            print(os.path.join(root, file))

In [ ]:
import os

print("Searching for Celeb-DF files...")
print("=" * 70)

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        path = os.path.join(root, file)

        if any(x in file.lower() for x in [
            "list",
            "label",
            "metadata",
            "real",
            "fake"
        ]):
            print(path)

In [ ]:
import os

CELEB_ROOT = "/kaggle/input/datasets/reubensuju/celeb-df-v2"

print("Celeb-DF root exists:", os.path.exists(CELEB_ROOT))

if os.path.exists(CELEB_ROOT):
    print("\nContents:")
    for item in os.listdir(CELEB_ROOT):
        print(item)

In [ ]:
for name in ["Celeb-real", "Celeb-synthesis", "YouTube-real"]:
    path = os.path.join(CELEB_ROOT, name)

    print(
        name,
        "exists:", os.path.exists(path)
    )

    if os.path.exists(path):
        files = [
            f for f in os.listdir(path)
            if f.lower().endswith(".mp4")
        ]

        print("  MP4 videos:", len(files))
        print("  Examples:", files[:3])

In [ ]:
import os
import cv2
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

# Step 4 output
STEP4_DIR = "/kaggle/working/step4_faces"

METADATA_PATH = os.path.join(
    STEP4_DIR,
    "step4_test_metadata.csv"
)

print("Metadata path:", METADATA_PATH)
print("Exists:", os.path.exists(METADATA_PATH))

In [ ]:
import os

print("Searching /kaggle/working for CSV files:\n")

for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

In [ ]:
print("\nSearching /kaggle/working for face images:\n")

count = 0

for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg", ".png")):
            count += 1
            if count <= 10:
                print(os.path.join(root, file))

print("\nTotal face images found:", count)

In [ ]:
import os

print("=== /kaggle/working contents ===")

for item in os.listdir("/kaggle/working"):
    print(item)

In [ ]:
print("\n=== Searching for Step 4 metadata ===")

for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if "step4" in file.lower() or "metadata" in file.lower():
            print(os.path.join(root, file))

In [ ]:
print("\n=== Searching for face images ===")

count = 0

for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg", ".png")):
            count += 1
            if count <= 20:
                print(os.path.join(root, file))

print("\nTotal face images:", count)

In [ ]:
print("=== Check Step 4 variables ===")

for v in [
    "FACES_DIR",
    "OUTPUT_DIR",
    "df",
    "results_df",
    "results",
    "mtcnn"
]:
    print(v, "exists:", v in globals())

In [ ]:
import os

print(
    os.path.exists(
        "/kaggle/working/step4_faces/step4_test_metadata.csv"
    )
)

In [ ]:
import facenet_pytorch

from facenet_pytorch import MTCNN

print("FaceNet-PyTorch:", facenet_pytorch.__version__)

In [ ]:
import os
import cv2
import torch
import torchvision
import numpy as np
import pandas as pd

from PIL import Image
from tqdm.auto import tqdm

print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("NumPy:", np.__version__)
print("OpenCV:", cv2.__version__)

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import facenet_pytorch

from facenet_pytorch import MTCNN

print("FaceNet-PyTorch:", facenet_pytorch.__version__)

In [ ]:
import facenet_pytorch
from facenet_pytorch import MTCNN

print("FaceNet-PyTorch imported successfully!")
print("MTCNN:", MTCNN)

In [ ]:
DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
mtcnn = MTCNN(
    keep_all=True,
    device=DEVICE,
    min_face_size=20,
    thresholds=[0.6, 0.7, 0.7],
    post_process=False
)

print("✅ MTCNN loaded successfully")

In [ ]:
import torch
import torchvision
import facenet_pytorch

print("Torch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("FaceNet-PyTorch:", facenet_pytorch.__file__)

In [ ]:
import os

import facenet_pytorch

package_dir = os.path.dirname(facenet_pytorch.__file__)

print("FaceNet-PyTorch location:")
print(package_dir)

print("\nChecking pretrained files:")

for name in ["pnet.pt", "rnet.pt", "onet.pt"]:
    path = os.path.join(package_dir, "data", name)
    print(name, "exists:", os.path.exists(path))

In [ ]:
import torch

# Compatibility workaround for older facenet-pytorch code
if not hasattr(torch.utils, "serialization"):
    import types
    torch.utils.serialization = types.ModuleType(
        "torch.utils.serialization"
    )

print("Compatibility patch applied.")
print("torch.utils.serialization exists:",
      hasattr(torch.utils, "serialization"))

In [ ]:
from facenet_pytorch import MTCNN

mtcnn = MTCNN(
    keep_all=True,
    device=DEVICE,
    min_face_size=20,
    thresholds=[0.6, 0.7, 0.7],
    post_process=False
)

print("✅ MTCNN loaded successfully")

In [ ]:
!pip uninstall -y facenet-pytorch
!pip install --no-cache-dir facenet-pytorch==2.6.0

In [1]:
import torch
import torchvision
import PIL

print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("Pillow:", PIL.__version__)

PyTorch: 2.2.2+cu121
Torchvision: 0.17.2+cu121
Pillow: 10.2.0

In [2]:
import facenet_pytorch
from facenet_pytorch import MTCNN

print("FaceNet-PyTorch imported successfully")
print("MTCNN:", MTCNN)

FaceNet-PyTorch imported successfully
MTCNN: <class 'facenet_pytorch.models.mtcnn.MTCNN'>

In [3]:
import torch

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Device: cuda
GPU: Tesla T4

In [4]:
mtcnn = MTCNN(
    keep_all=True,
    device=DEVICE,
    min_face_size=20,
    thresholds=[0.6, 0.7, 0.7],
    post_process=False
)

print("✅ MTCNN loaded successfully")

✅ MTCNN loaded successfully

In [5]:
import os
import pandas as pd

CSV_PATH = None

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file == "clean_video_list.csv":
            CSV_PATH = os.path.join(root, file)
            break
    if CSV_PATH:
        break

print("CSV path:", CSV_PATH)

CSV path: None

In [6]:
!git clone https://github.com/NancyKashyap29/deepfake-detector-project.git /kaggle/working/project_repo

Cloning into '/kaggle/working/project_repo'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 1), reused 7 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 821.45 KiB | 9.33 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [7]:
import os

for root, dirs, files in os.walk("/kaggle/working/project_repo"):
    for file in files:
        if file == "clean_video_list.csv":
            print("FOUND:")
            print(os.path.join(root, file))

FOUND:
/kaggle/working/project_repo/logs/clean_video_list.csv

In [8]:
CSV_PATH = "/kaggle/working/project_repo/data/clean_video_list.csv"

df = pd.read_csv(CSV_PATH)

print("Total videos:", len(df))
print(df.columns.tolist())
display(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/project_repo/data/clean_video_list.csv'

In [9]:
import os

CSV_PATH = None

for root, dirs, files in os.walk("/kaggle/working/project_repo"):
    if "clean_video_list.csv" in files:
        CSV_PATH = os.path.join(
            root,
            "clean_video_list.csv"
        )
        break

print("CSV_PATH:", CSV_PATH)

CSV_PATH: /kaggle/working/project_repo/logs/clean_video_list.csv

In [10]:
import pandas as pd

df = pd.read_csv(CSV_PATH)

print("Total videos:", len(df))
print("Columns:", df.columns.tolist())

display(df.head())

Total videos: 13529
Columns: ['video_path']

                             video_path
0  data/raw\cel\Celeb-real\id0_0000.mp4
1  data/raw\cel\Celeb-real\id0_0001.mp4
2  data/raw\cel\Celeb-real\id0_0002.mp4
3  data/raw\cel\Celeb-real\id0_0003.mp4
4  data/raw\cel\Celeb-real\id0_0004.mp4

In [11]:
print("Total videos:", len(df))
print("Columns:", df.columns.tolist())
display(df.head())

Total videos: 13529
Columns: ['video_path']

                             video_path
0  data/raw\cel\Celeb-real\id0_0000.mp4
1  data/raw\cel\Celeb-real\id0_0001.mp4
2  data/raw\cel\Celeb-real\id0_0002.mp4
3  data/raw\cel\Celeb-real\id0_0003.mp4
4  data/raw\cel\Celeb-real\id0_0004.mp4

In [12]:
import os

print("Searching for dataset roots...")

for root, dirs, files in os.walk("/kaggle/input"):
    if "Celeb-real" in dirs:
        print("Celeb-DF location:", root)

    if "FaceForensics++_C23" in dirs:
        print("FF++ location:", root)

Searching for dataset roots...
FF++ location: /kaggle/input/datasets/xdxd003/ff-c23
Celeb-DF location: /kaggle/input/datasets/reubensuju/celeb-df-v2

In [15]:
def get_kaggle_video_path(csv_path):

    csv_path = str(csv_path).replace("\\", "/")

    if "/cel/" in csv_path:
        relative = csv_path.split("/cel/", 1)[1]
        return os.path.join(CELEB_ROOT, relative)

    if "/ff/" in csv_path:
        relative = csv_path.split("/ff/", 1)[1]
        return os.path.join(FF_ROOT, relative)

    return None

In [14]:
CELEB_ROOT = "/kaggle/input/datasets/reubensuju/celeb-df-v2"

FF_ROOT = "/kaggle/input/datasets/xdxd003/ff-c23/FaceForensics++_C23"

print("Celeb-DF exists:", os.path.exists(CELEB_ROOT))
print("FF++ exists:", os.path.exists(FF_ROOT))

Celeb-DF exists: True
FF++ exists: True

In [16]:
test_csv_path = df.iloc[0]["video_path"]

test_video_path = get_kaggle_video_path(
    test_csv_path
)

print("CSV path:")
print(test_csv_path)

print("\nKaggle path:")
print(test_video_path)

print("\nExists:")
print(os.path.exists(test_video_path))

CSV path:
data/raw\cel\Celeb-real\id0_0000.mp4

Kaggle path:
/kaggle/input/datasets/reubensuju/celeb-df-v2/Celeb-real/id0_0000.mp4

Exists:
True

In [17]:
import torch

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Device: cuda
GPU: Tesla T4

In [18]:
from facenet_pytorch import MTCNN

mtcnn = MTCNN(
    keep_all=True,
    device=DEVICE,
    min_face_size=20,
    thresholds=[0.6, 0.7, 0.7],
    post_process=False
)

print("✅ MTCNN loaded successfully")

✅ MTCNN loaded successfully

In [19]:
OUTPUT_DIR = "/kaggle/working/step4_faces"

FACES_DIR = os.path.join(
    OUTPUT_DIR,
    "faces"
)

os.makedirs(
    FACES_DIR,
    exist_ok=True
)

print("OUTPUT_DIR:", OUTPUT_DIR)
print("FACES_DIR:", FACES_DIR)

OUTPUT_DIR: /kaggle/working/step4_faces
FACES_DIR: /kaggle/working/step4_faces/faces

In [20]:
NUM_TEST_VIDEOS = 10
FRAME_INTERVAL = 10
MIN_CONFIDENCE = 0.90

print("Videos to test:", NUM_TEST_VIDEOS)
print("Frame interval:", FRAME_INTERVAL)
print("Minimum confidence:", MIN_CONFIDENCE)

Videos to test: 10
Frame interval: 10
Minimum confidence: 0.9

In [23]:
import cv2
import pandas as pd
import numpy as np
from PIL import Image
from tqdm.auto import tqdm

In [24]:
print("STEP 4 TEST COMPLETE")

STEP 4 TEST COMPLETE

In [26]:
STEP4_METADATA = (
    "/kaggle/working/step4_faces/"
    "step4_test_metadata.csv"
)

print(
    "Metadata exists:",
    os.path.exists(STEP4_METADATA)
)

Metadata exists: False

In [27]:
import os

print("step4_faces exists:",
      os.path.exists("/kaggle/working/step4_faces"))

print("\nWorking directory:")
print(os.listdir("/kaggle/working"))

step4_faces exists: True

Working directory:
['clean_video_list.csv', 'step4_faces', 'project_repo', '.virtual_documents']

In [28]:
STEP4_DIR = "/kaggle/working/step4_faces"
FACES_DIR = os.path.join(STEP4_DIR, "faces")

os.makedirs(FACES_DIR, exist_ok=True)

print("Created:")
print(STEP4_DIR)
print(FACES_DIR)

Created:
/kaggle/working/step4_faces
/kaggle/working/step4_faces/faces

In [29]:
STEP4_METADATA = (
    "/kaggle/working/step4_faces/"
    "step4_test_metadata.csv"
)

print(
    "Metadata exists:",
    os.path.exists(STEP4_METADATA)
)

Metadata exists: False

In [30]:
STEP4_METADATA = (
    "/kaggle/working/step4_faces/"
    "step4_test_metadata.csv"
)

print(
    "Metadata exists:",
    os.path.exists(STEP4_METADATA)
)

Metadata exists: False

In [32]:
print("=== STEP 4 OUTPUT CHECK ===")

print(
    "Step 4 directory exists:",
    os.path.exists(STEP4_DIR)
)

print(
    "Faces directory exists:",
    os.path.exists(FACES_DIR)
)

print(
    "Metadata exists:",
    os.path.exists(
        os.path.join(
            STEP4_DIR,
            "step4_test_metadata.csv"
        )
    )
)

# Count face images
face_count = 0

for root, dirs, files in os.walk(FACES_DIR):
    for file in files:
        if file.lower().endswith(
            (".jpg", ".jpeg", ".png")
        ):
            face_count += 1

print("Face images:", face_count)

=== STEP 4 OUTPUT CHECK ===
Step 4 directory exists: True
Faces directory exists: True
Metadata exists: False
Face images: 0

In [34]:
print("Variables/functions currently available:")

for name in [
    "df",
    "mtcnn",
    "DEVICE",
    "STEP4_DIR",
    "FACES_DIR",
    "get_kaggle_video_path"
]:
    print(name, "->", name in globals())

Variables/functions currently available:
df -> True
mtcnn -> True
DEVICE -> True
STEP4_DIR -> True
FACES_DIR -> True
get_kaggle_video_path -> True

In [35]:
import cv2
import os
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

# Step 4 test settings
NUM_TEST_VIDEOS = 10
FRAME_INTERVAL = 10
MIN_CONFIDENCE = 0.90

metadata = []

test_df = df.head(NUM_TEST_VIDEOS).copy()

print("Testing videos:", len(test_df))

for idx, row in tqdm(
    test_df.iterrows(),
    total=len(test_df)
):
    
    video_path = get_kaggle_video_path(
        row["video_path"]
    )

    if video_path is None or not os.path.exists(video_path):
        print("Video not found:", video_path)
        continue

    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Could not open:", video_path)
        continue

    frame_number = 0

    while True:

        ret, frame = cap.read()

        if not ret:
            break

        if frame_number % FRAME_INTERVAL != 0:
            frame_number += 1
            continue

        # Convert BGR → RGB
        rgb = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2RGB
        )

        # Detect faces
        boxes, probs = mtcnn.detect(rgb)

        if boxes is not None:

            for face_idx, (box, prob) in enumerate(
                zip(boxes, probs)
            ):

                if prob is None or prob < MIN_CONFIDENCE:
                    continue

                x1, y1, x2, y2 = box.astype(int)

                # Keep coordinates inside image
                h, w = frame.shape[:2]

                x1 = max(0, x1)
                y1 = max(0, y1)
                x2 = min(w, x2)
                y2 = min(h, y2)

                if x2 <= x1 or y2 <= y1:
                    continue

                face = frame[
                    y1:y2,
                    x1:x2
                ]

                if face.size == 0:
                    continue

                face_width = x2 - x1
                face_height = y2 - y1

                # Save face
                face_filename = (
                    f"video_{idx}_"
                    f"frame_{frame_number}_"
                    f"face_{face_idx}.jpg"
                )

                face_path = os.path.join(
                    FACES_DIR,
                    face_filename
                )

                cv2.imwrite(
                    face_path,
                    face
                )

                metadata.append({
                    "video_path": row["video_path"],
                    "frame_number": frame_number,
                    "face_path": face_path,
                    "confidence": float(prob),
                    "x1": x1,
                    "y1": y1,
                    "x2": x2,
                    "y2": y2,
                    "face_width": face_width,
                    "face_height": face_height
                })

        frame_number += 1

    cap.release()


# Create metadata DataFrame
step4_df = pd.DataFrame(metadata)

# Save Step 4 metadata
STEP4_METADATA = os.path.join(
    STEP4_DIR,
    "step4_test_metadata.csv"
)

step4_df.to_csv(
    STEP4_METADATA,
    index=False
)

print("\n" + "=" * 50)
print("STEP 4 TEST COMPLETE")
print("=" * 50)

print("Videos tested:", len(test_df))
print("Face crops saved:", len(step4_df))
print("Metadata:", STEP4_METADATA)

Testing videos: 10

  0%|          | 0/10 [00:00<?, ?it/s]

==================================================
STEP 4 TEST COMPLETE
==================================================
Videos tested: 10
Face crops saved: 450
Metadata: /kaggle/working/step4_faces/step4_test_metadata.csv

In [36]:
print("Metadata exists:",
      os.path.exists(STEP4_METADATA))

print("Face images:",
      len([
          f for f in os.listdir(FACES_DIR)
          if f.lower().endswith(".jpg")
      ]))

print("\nMetadata rows:", len(step4_df))

display(step4_df.head())

Metadata exists: True
Face images: 450

Metadata rows: 450

,video_path,frame_number,face_path,confidence,x1,y1,x2,y2,face_width,face_height
0,data/raw\cel\Celeb-real\id0_0000.mp4,0,/kaggle/working/step4_faces/faces/video_0_fram...,1.000000,555,112,642,226,87,114
1,data/raw\cel\Celeb-real\id0_0000.mp4,10,/kaggle/working/step4_faces/faces/video_0_fram...,0.999982,555,114,639,226,84,112
2,data/raw\cel\Celeb-real\id0_0000.mp4,20,/kaggle/working/step4_faces/faces/video_0_fram...,0.999990,545,111,629,224,84,113
3,data/raw\cel\Celeb-real\id0_0000.mp4,30,/kaggle/working/step4_faces/faces/video_0_fram...,0.999985,520,110,605,216,85,106
4,data/raw\cel\Celeb-real\id0_0000.mp4,40,/kaggle/working/step4_faces/faces/video_0_fram...,0.999999,497,108,583,216,86,108

In [37]:
import pandas as pd
import os

STEP4_METADATA = os.path.join(
    STEP4_DIR,
    "step4_test_metadata.csv"
)

step4_df = pd.read_csv(STEP4_METADATA)

print("Step 4 metadata loaded")
print("Rows:", len(step4_df))
print("Columns:")
print(step4_df.columns.tolist())

display(step4_df.head())

Step 4 metadata loaded
Rows: 450
Columns:
['video_path', 'frame_number', 'face_path', 'confidence', 'x1', 'y1', 'x2', 'y2', 'face_width', 'face_height']

,video_path,frame_number,face_path,confidence,x1,y1,x2,y2,face_width,face_height
0,data/raw\cel\Celeb-real\id0_0000.mp4,0,/kaggle/working/step4_faces/faces/video_0_fram...,1.000000,555,112,642,226,87,114
1,data/raw\cel\Celeb-real\id0_0000.mp4,10,/kaggle/working/step4_faces/faces/video_0_fram...,0.999982,555,114,639,226,84,112
2,data/raw\cel\Celeb-real\id0_0000.mp4,20,/kaggle/working/step4_faces/faces/video_0_fram...,0.999990,545,111,629,224,84,113
3,data/raw\cel\Celeb-real\id0_0000.mp4,30,/kaggle/working/step4_faces/faces/video_0_fram...,0.999985,520,110,605,216,85,106
4,data/raw\cel\Celeb-real\id0_0000.mp4,40,/kaggle/working/step4_faces/faces/video_0_fram...,0.999999,497,108,583,216,86,108

In [39]:
step4_df["file_exists"] = step4_df["face_path"].apply(
    os.path.exists
)

print("Total face crops:", len(step4_df))
print(
    "Face images found:",
    step4_df["file_exists"].sum()
)
print(
    "Missing face images:",
    (~step4_df["file_exists"]).sum()
)

Total face crops: 450
Face images found: 450
Missing face images: 0

In [41]:
import cv2
import numpy as np
from tqdm.auto import tqdm

def calculate_blur_score(image_path):

    if not os.path.exists(image_path):
        return np.nan

    image = cv2.imread(image_path)

    if image is None:
        return np.nan

    gray = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2GRAY
    )

    return float(
        cv2.Laplacian(
            gray,
            cv2.CV_64F
        ).var()
    )

In [42]:
import cv2
import numpy as np
from tqdm.auto import tqdm

def calculate_blur_score(image_path):

    if not os.path.exists(image_path):
        return np.nan

    image = cv2.imread(image_path)

    if image is None:
        return np.nan

    gray = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2GRAY
    )

    return float(
        cv2.Laplacian(
            gray,
            cv2.CV_64F
        ).var()
    )

In [43]:
tqdm.pandas()

step4_df["blur_score"] = step4_df[
    "face_path"
].progress_apply(
    calculate_blur_score
)

print("✅ Blur scores calculated")

display(
    step4_df[
        [
            "face_path",
            "blur_score"
        ]
    ].head(10)
)

  0%|          | 0/450 [00:00<?, ?it/s]

✅ Blur scores calculated

                                           face_path  blur_score
0  /kaggle/working/step4_faces/faces/video_0_fram...   54.904705
1  /kaggle/working/step4_faces/faces/video_0_fram...   45.307807
2  /kaggle/working/step4_faces/faces/video_0_fram...   45.908019
3  /kaggle/working/step4_faces/faces/video_0_fram...   44.649290
4  /kaggle/working/step4_faces/faces/video_0_fram...   40.887297
5  /kaggle/working/step4_faces/faces/video_0_fram...   48.879530
6  /kaggle/working/step4_faces/faces/video_0_fram...   47.803385
7  /kaggle/working/step4_faces/faces/video_0_fram...   37.599472
8  /kaggle/working/step4_faces/faces/video_0_fram...   35.019775
9  /kaggle/working/step4_faces/faces/video_0_fram...   35.637698

In [44]:
print("Blur score statistics:")

display(
    step4_df["blur_score"].describe()
)

print("\nBlur score percentiles:")

display(
    step4_df["blur_score"].quantile([
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ])
)

Blur score statistics:

count    450.000000
mean      54.555750
std       29.240513
min       13.302584
25%       36.316010
50%       46.976332
75%       66.901470
max      262.828076
Name: blur_score, dtype: float64

Blur score percentiles:

0.01     15.922563
0.05     18.189524
0.10     24.278423
0.25     36.316010
0.50     46.976332
0.75     66.901470
0.90     94.689387
0.95    108.459057
0.99    143.288013
Name: blur_score, dtype: float64

In [45]:
BLUR_THRESHOLD = 50

print("Blur threshold:", BLUR_THRESHOLD)

Blur threshold: 50

In [46]:
step4_df["blur_pass"] = (
    step4_df["blur_score"] >= BLUR_THRESHOLD
)

print("Total face crops:", len(step4_df))
print(
    "Passed blur:",
    step4_df["blur_pass"].sum()
)
print(
    "Dropped due to blur:",
    (~step4_df["blur_pass"]).sum()
)

Total face crops: 450
Passed blur: 205
Dropped due to blur: 245

In [47]:
total_faces = len(step4_df)

blur_dropped = (
    ~step4_df["blur_pass"]
).sum()

print(
    "Dropped due to blur:",
    blur_dropped
)

print(
    "Percentage dropped due to blur:",
    round(
        blur_dropped / total_faces * 100,
        2
    ),
    "%"
)

Dropped due to blur: 245
Percentage dropped due to blur: 54.44 %

In [48]:
print("Faces just below threshold:")

display(
    step4_df[
        step4_df["blur_score"] < BLUR_THRESHOLD
    ].sort_values(
        "blur_score",
        ascending=False
    ).head(10)
)

print("\nFaces just above threshold:")

display(
    step4_df[
        step4_df["blur_score"] >= BLUR_THRESHOLD
    ].sort_values(
        "blur_score"
    ).head(10)
)

Faces just below threshold:

,video_path,frame_number,face_path,confidence,x1,y1,x2,y2,face_width,face_height,file_exists,blur_score,blur_pass
148,data/raw\cel\Celeb-real\id0_0003.mp4,350,/kaggle/working/step4_faces/faces/video_3_fram...,0.999995,390,181,539,382,149,201,True,49.821372,False
143,data/raw\cel\Celeb-real\id0_0003.mp4,300,/kaggle/working/step4_faces/faces/video_3_fram...,0.999910,395,152,539,363,144,211,True,49.582154,False
29,data/raw\cel\Celeb-real\id0_0000.mp4,290,/kaggle/working/step4_faces/faces/video_0_fram...,0.999934,505,101,596,224,91,123,True,49.569108,False
238,data/raw\cel\Celeb-real\id0_0005.mp4,390,/kaggle/working/step4_faces/faces/video_5_fram...,0.999954,331,131,490,339,159,208,True,49.254781,False
249,data/raw\cel\Celeb-real\id0_0006.mp4,40,/kaggle/working/step4_faces/faces/video_6_fram...,0.999999,432,119,536,261,104,142,True,49.141478,False
5,data/raw\cel\Celeb-real\id0_0000.mp4,50,/kaggle/working/step4_faces/faces/video_0_fram...,0.999577,480,114,562,220,82,106,True,48.879530,False
411,data/raw\cel\Celeb-real\id0_0009.mp4,130,/kaggle/working/step4_faces/faces/video_9_fram...,0.999986,441,149,536,252,95,103,True,48.703011,False
138,data/raw\cel\Celeb-real\id0_0003.mp4,250,/kaggle/working/step4_faces/faces/video_3_fram...,0.999990,416,205,550,394,134,189,True,48.675095,False
14,data/raw\cel\Celeb-real\id0_0000.mp4,140,/kaggle/working/step4_faces/faces/video_0_fram...,0.999938,483,121,573,232,90,111,True,48.661028,False
211,data/raw\cel\Celeb-real\id0_0005.mp4,120,/kaggle/working/step4_faces/faces/video_5_fram...,0.999917,329,90,484,297,155,207,True,48.430913,False

Faces just above threshold:

,video_path,frame_number,face_path,confidence,x1,y1,x2,y2,face_width,face_height,file_exists,blur_score,blur_pass
414,data/raw\cel\Celeb-real\id0_0009.mp4,160,/kaggle/working/step4_faces/faces/video_9_fram...,0.999999,425,65,526,197,101,132,True,50.040771,True
287,data/raw\cel\Celeb-real\id0_0006.mp4,410,/kaggle/working/step4_faces/faces/video_6_fram...,0.999983,404,145,509,286,105,141,True,50.221507,True
49,data/raw\cel\Celeb-real\id0_0001.mp4,20,/kaggle/working/step4_faces/faces/video_1_fram...,0.999851,387,120,503,266,116,146,True,50.259800,True
171,data/raw\cel\Celeb-real\id0_0004.mp4,50,/kaggle/working/step4_faces/faces/video_4_fram...,0.999997,398,106,553,313,155,207,True,50.915027,True
187,data/raw\cel\Celeb-real\id0_0004.mp4,210,/kaggle/working/step4_faces/faces/video_4_fram...,0.999996,346,97,514,319,168,222,True,51.115227,True
186,data/raw\cel\Celeb-real\id0_0004.mp4,200,/kaggle/working/step4_faces/faces/video_4_fram...,0.999997,344,99,512,317,168,218,True,51.373084,True
254,data/raw\cel\Celeb-real\id0_0006.mp4,90,/kaggle/working/step4_faces/faces/video_6_fram...,1.000000,426,133,526,270,100,137,True,51.501004,True
437,data/raw\cel\Celeb-real\id0_0009.mp4,390,/kaggle/working/step4_faces/faces/video_9_fram...,0.999995,429,79,539,221,110,142,True,51.575444,True
250,data/raw\cel\Celeb-real\id0_0006.mp4,50,/kaggle/working/step4_faces/faces/video_6_fram...,0.999983,432,116,531,258,99,142,True,51.647499,True
438,data/raw\cel\Celeb-real\id0_0009.mp4,400,/kaggle/working/step4_faces/faces/video_9_fram...,1.000000,436,81,546,221,110,140,True,51.717440,True

In [49]:
print("Face width statistics:")
display(step4_df["face_width"].describe())

print("\nFace height statistics:")
display(step4_df["face_height"].describe())

Face width statistics:

count    450.000000
mean     131.602222
std       28.908110
min       24.000000
25%      104.000000
50%      138.000000
75%      158.000000
max      197.000000
Name: face_width, dtype: float64

Face height statistics:

count    450.000000
mean     176.802222
std       40.628235
min       31.000000
25%      141.000000
50%      188.000000
75%      211.000000
max      268.000000
Name: face_height, dtype: float64

In [50]:
MIN_FACE_WIDTH = 64
MIN_FACE_HEIGHT = 64

print("Minimum face width:", MIN_FACE_WIDTH)
print("Minimum face height:", MIN_FACE_HEIGHT)

Minimum face width: 64
Minimum face height: 64

In [51]:
step4_df["size_pass"] = (
    (step4_df["face_width"] >= MIN_FACE_WIDTH) &
    (step4_df["face_height"] >= MIN_FACE_HEIGHT)
)

print("Total faces:", len(step4_df))

print(
    "Passed size:",
    step4_df["size_pass"].sum()
)

print(
    "Dropped due to size:",
    (~step4_df["size_pass"]).sum()
)

Total faces: 450
Passed size: 447
Dropped due to size: 3

In [52]:
size_dropped = (
    ~step4_df["size_pass"]
).sum()

print(
    "Dropped due to size:",
    size_dropped
)

print(
    "Percentage dropped due to size:",
    round(
        size_dropped / len(step4_df) * 100,
        2
    ),
    "%"
)

Dropped due to size: 3
Percentage dropped due to size: 0.67 %

In [53]:
size_dropped = (
    ~step4_df["size_pass"]
).sum()

print(
    "Dropped due to size:",
    size_dropped
)

print(
    "Percentage dropped due to size:",
    round(
        size_dropped / len(step4_df) * 100,
        2
    ),
    "%"
)

Dropped due to size: 3
Percentage dropped due to size: 0.67 %

In [54]:
step4_df["quality_pass"] = (
    step4_df["blur_pass"] &
    step4_df["size_pass"]
)

filtered_df = step4_df[
    step4_df["quality_pass"]
].copy()

print("=" * 60)
print("QUALITY FILTERING RESULT")
print("=" * 60)

print("Faces before filtering:", len(step4_df))
print("Faces remaining:", len(filtered_df))
print(
    "Total dropped:",
    len(step4_df) - len(filtered_df)
)

============================================================
QUALITY FILTERING RESULT
============================================================
Faces before filtering: 450
Faces remaining: 202
Total dropped: 248

In [55]:
total_in = len(step4_df)

dropped_blur = (
    ~step4_df["blur_pass"]
).sum()

dropped_size = (
    step4_df["blur_pass"] &
    ~step4_df["size_pass"]
).sum()

remaining = (
    step4_df["quality_pass"]
).sum()

print("=" * 60)
print("STEP 5 DROP COUNTS")
print("=" * 60)

print("Total faces in:", total_in)
print("Dropped due to blur:", dropped_blur)
print("Dropped due to size:", dropped_size)
print("Remaining:", remaining)

============================================================
STEP 5 DROP COUNTS
============================================================
Total faces in: 450
Dropped due to blur: 245
Dropped due to size: 3
Remaining: 202

In [56]:
print(
    "Overall percentage dropped:",
    round(
        (total_in - remaining)
        / total_in * 100,
        2
    ),
    "%"
)

print(
    "Overall percentage remaining:",
    round(
        remaining / total_in * 100,
        2
    ),
    "%"
)

Overall percentage dropped: 55.11 %
Overall percentage remaining: 44.89 %

In [57]:
summary = pd.DataFrame([
    {
        "category": "Overall",
        "total_in": total_in,
        "dropped_blur": int(dropped_blur),
        "dropped_size": int(dropped_size),
        "remaining": int(remaining)
    }
])

display(summary)

  category  total_in  dropped_blur  dropped_size  remaining
0  Overall       450           245             3        202

In [58]:
print("Label columns:")
print(step4_df.columns.tolist())

Label columns:
['video_path', 'frame_number', 'face_path', 'confidence', 'x1', 'y1', 'x2', 'y2', 'face_width', 'face_height', 'file_exists', 'blur_score', 'blur_pass', 'size_pass', 'quality_pass']

In [59]:
print("BEFORE filtering:")

display(
    step4_df["label_name"]
    .value_counts(dropna=False)
)

print("\nAFTER filtering:")

display(
    filtered_df["label_name"]
    .value_counts(dropna=False)
)

BEFORE filtering:

KeyError: 'label_name'

In [60]:
# Create a mapping from video_path → label
label_map = dict(
    zip(
        df["video_path"].astype(str),
        df["label"].astype(str).str.upper()
    )
)

# Add label to Step 4 metadata
step4_df["label_name"] = (
    step4_df["video_path"]
    .astype(str)
    .map(label_map)
)

print("Labels added.")
print(
    step4_df["label_name"]
    .value_counts(dropna=False)
)

KeyError: 'label'

In [61]:
# Create a mapping from video_path → label
label_map = dict(
    zip(
        df["video_path"].astype(str),
        df["label"].astype(str).str.upper()
    )
)

# Add label to Step 4 metadata
step4_df["label_name"] = (
    step4_df["video_path"]
    .astype(str)
    .map(label_map)
)

print("Labels added.")
print(
    step4_df["label_name"]
    .value_counts(dropna=False)
)

KeyError: 'label'

In [62]:
print("df columns:")
print(df.columns.tolist())

print("\nstep4_df columns:")
print(step4_df.columns.tolist())

df columns:
['video_path']

step4_df columns:
['video_path', 'frame_number', 'face_path', 'confidence', 'x1', 'y1', 'x2', 'y2', 'face_width', 'face_height', 'file_exists', 'blur_score', 'blur_pass', 'size_pass', 'quality_pass']

In [64]:
print(df["video_path"].head(20).to_string(index=False))

 data/raw\cel\Celeb-real\id0_0000.mp4
 data/raw\cel\Celeb-real\id0_0001.mp4
 data/raw\cel\Celeb-real\id0_0002.mp4
 data/raw\cel\Celeb-real\id0_0003.mp4
 data/raw\cel\Celeb-real\id0_0004.mp4
 data/raw\cel\Celeb-real\id0_0005.mp4
 data/raw\cel\Celeb-real\id0_0006.mp4
 data/raw\cel\Celeb-real\id0_0007.mp4
 data/raw\cel\Celeb-real\id0_0008.mp4
 data/raw\cel\Celeb-real\id0_0009.mp4
data/raw\cel\Celeb-real\id10_0000.mp4
data/raw\cel\Celeb-real\id10_0001.mp4
data/raw\cel\Celeb-real\id10_0002.mp4
data/raw\cel\Celeb-real\id10_0003.mp4
data/raw\cel\Celeb-real\id10_0004.mp4
data/raw\cel\Celeb-real\id10_0005.mp4
data/raw\cel\Celeb-real\id10_0006.mp4
data/raw\cel\Celeb-real\id10_0007.mp4
data/raw\cel\Celeb-real\id10_0008.mp4
data/raw\cel\Celeb-real\id10_0009.mp4

In [63]:
display(df.head())

                             video_path
0  data/raw\cel\Celeb-real\id0_0000.mp4
1  data/raw\cel\Celeb-real\id0_0001.mp4
2  data/raw\cel\Celeb-real\id0_0002.mp4
3  data/raw\cel\Celeb-real\id0_0003.mp4
4  data/raw\cel\Celeb-real\id0_0004.mp4

In [65]:
print(step4_df["video_path"].head(20).to_string(index=False))

data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4
data/raw\cel\Celeb-real\id0_0000.mp4

In [66]:
print(
    df["video_path"]
    .astype(str)
    .str.split("/")
    .str[:3]
    .apply(lambda x: "/".join(x))
    .value_counts()
    .head(20)
)

video_path
data/raw\FaceForensics++_C23\original\999.mp4    1
data/raw\cel\Celeb-real\id0_0000.mp4             1
data/raw\cel\Celeb-real\id0_0001.mp4             1
data/raw\cel\Celeb-real\id0_0002.mp4             1
data/raw\cel\Celeb-real\id0_0003.mp4             1
data/raw\cel\Celeb-real\id0_0004.mp4             1
data/raw\cel\Celeb-real\id0_0005.mp4             1
data/raw\cel\Celeb-real\id0_0006.mp4             1
data/raw\cel\Celeb-real\id0_0007.mp4             1
data/raw\cel\Celeb-real\id0_0008.mp4             1
data/raw\cel\Celeb-real\id0_0009.mp4             1
data/raw\cel\Celeb-real\id10_0000.mp4            1
data/raw\cel\Celeb-real\id10_0001.mp4            1
data/raw\cel\Celeb-real\id10_0002.mp4            1
data/raw\cel\Celeb-real\id10_0003.mp4            1
data/raw\cel\Celeb-real\id10_0004.mp4            1
data/raw\cel\Celeb-real\id10_0005.mp4            1
data/raw\cel\Celeb-real\id10_0006.mp4            1
data/raw\cel\Celeb-real\id10_0007.mp4            1
data/raw\cel\Celeb-real\id10_0008.mp4            1
Name: count, dtype: int64

In [67]:
import os
import numpy as np

def get_label_from_path(path):
    path = str(path).replace("\\", "/").lower()

    # Celeb-DF
    if "/celeb-real/" in path:
        return "REAL"

    if "/celeb-synthesis/" in path:
        return "FAKE"

    # FaceForensics++ original videos
    if "/original/" in path:
        return "REAL"

    # FaceForensics++ manipulated videos
    fake_folders = [
        "/deepfakes/",
        "/faceswap/",
        "/faceshifter/",
        "/face2face/",
        "/neuraltextures/"
    ]

    for folder in fake_folders:
        if folder in path:
            return "FAKE"

    return np.nan


step4_df["label_name"] = step4_df["video_path"].apply(
    get_label_from_path
)

print("Label distribution:")
print(
    step4_df["label_name"]
    .value_counts(dropna=False)
)

Label distribution:
label_name
REAL    450
Name: count, dtype: int64

In [68]:
print(
    "Missing/unknown labels:",
    step4_df["label_name"].isna().sum()
)

Missing/unknown labels: 0

In [69]:
step4_df["label"] = step4_df["label_name"].map({
    "REAL": 0,
    "FAKE": 1
})

print("\nFinal labels:")
print(step4_df["label_name"].value_counts())

Final labels:
label_name
REAL    450
Name: count, dtype: int64

In [70]:
filtered_df = step4_df[
    step4_df["quality_pass"]
].copy()

print("Before filtering:", len(step4_df))
print("After filtering:", len(filtered_df))

Before filtering: 450
After filtering: 202

In [71]:
print("=== BEFORE FILTERING ===")
print(
    step4_df["label_name"].value_counts()
)

print("\n=== AFTER FILTERING ===")
print(
    filtered_df["label_name"].value_counts()
)

=== BEFORE FILTERING ===
label_name
REAL    450
Name: count, dtype: int64

=== AFTER FILTERING ===
label_name
REAL    202
Name: count, dtype: int64

In [72]:
print("=== AFTER FILTERING (%) ===")

print(
    filtered_df["label_name"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

=== AFTER FILTERING (%) ===
label_name
REAL    100.0
Name: proportion, dtype: float64

In [73]:
print("Total videos:", len(df))
print("Columns:", df.columns.tolist())
display(df.head())

Total videos: 13529
Columns: ['video_path']

                             video_path
0  data/raw\cel\Celeb-real\id0_0000.mp4
1  data/raw\cel\Celeb-real\id0_0001.mp4
2  data/raw\cel\Celeb-real\id0_0002.mp4
3  data/raw\cel\Celeb-real\id0_0003.mp4
4  data/raw\cel\Celeb-real\id0_0004.mp4

In [74]:
import os
import numpy as np

def get_label_from_path(path):
    path = str(path).replace("\\", "/").lower()

    # Celeb-DF
    if "/celeb-real/" in path:
        return "REAL"

    if "/celeb-synthesis/" in path:
        return "FAKE"

    # FaceForensics++ original
    if "/original/" in path:
        return "REAL"

    # FaceForensics++ manipulated
    fake_folders = [
        "/deepfakes/",
        "/faceswap/",
        "/faceshifter/",
        "/face2face/",
        "/neuraltextures/"
    ]

    for folder in fake_folders:
        if folder in path:
            return "FAKE"

    return np.nan


df["label_name"] = df["video_path"].apply(
    get_label_from_path
)

print("Class distribution:")
print(df["label_name"].value_counts(dropna=False))

Class distribution:
label_name
FAKE    10639
REAL     1590
NaN      1300
Name: count, dtype: int64

In [75]:
real_df = df[
    df["label_name"] == "REAL"
].copy()

fake_df = df[
    df["label_name"] == "FAKE"
].copy()

print("Available REAL videos:", len(real_df))
print("Available FAKE videos:", len(fake_df))

Available REAL videos: 1590
Available FAKE videos: 10639

In [76]:
NUM_REAL = 10
NUM_FAKE = 10

test_real = real_df.sample(
    n=NUM_REAL,
    random_state=42
)

test_fake = fake_df.sample(
    n=NUM_FAKE,
    random_state=42
)

test_df = pd.concat(
    [test_real, test_fake],
    ignore_index=True
)

test_df = test_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Total test videos:", len(test_df))

print("\nTest distribution:")
print(test_df["label_name"].value_counts())

Total test videos: 20

Test distribution:
label_name
REAL    10
FAKE    10
Name: count, dtype: int64

In [77]:
STEP4_BALANCED_DIR = "/kaggle/working/step4_balanced"

BALANCED_FACES_DIR = os.path.join(
    STEP4_BALANCED_DIR,
    "faces"
)

os.makedirs(
    BALANCED_FACES_DIR,
    exist_ok=True
)

print("Step 4 balanced directory:")
print(STEP4_BALANCED_DIR)

print("\nFaces directory:")
print(BALANCED_FACES_DIR)

Step 4 balanced directory:
/kaggle/working/step4_balanced

Faces directory:
/kaggle/working/step4_balanced/faces

In [78]:
import cv2
import os
import pandas as pd
from tqdm.auto import tqdm

FRAME_INTERVAL = 10
MIN_CONFIDENCE = 0.90

balanced_metadata = []

for idx, row in tqdm(
    test_df.iterrows(),
    total=len(test_df)
):

    video_path = get_kaggle_video_path(
        row["video_path"]
    )

    if video_path is None or not os.path.exists(video_path):
        print("Video not found:", row["video_path"])
        continue

    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Could not open:", video_path)
        continue

    frame_number = 0

    while True:

        ret, frame = cap.read()

        if not ret:
            break

        if frame_number % FRAME_INTERVAL != 0:
            frame_number += 1
            continue

        rgb = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2RGB
        )

        boxes, probs = mtcnn.detect(rgb)

        if boxes is not None:

            for face_idx, (box, prob) in enumerate(
                zip(boxes, probs)
            ):

                if prob is None or prob < MIN_CONFIDENCE:
                    continue

                x1, y1, x2, y2 = box.astype(int)

                h, w = frame.shape[:2]

                x1 = max(0, x1)
                y1 = max(0, y1)
                x2 = min(w, x2)
                y2 = min(h, y2)

                if x2 <= x1 or y2 <= y1:
                    continue

                face = frame[
                    y1:y2,
                    x1:x2
                ]

                if face.size == 0:
                    continue

                face_width = x2 - x1
                face_height = y2 - y1

                filename = (
                    f"video_{idx}_"
                    f"frame_{frame_number}_"
                    f"face_{face_idx}.jpg"
                )

                face_path = os.path.join(
                    BALANCED_FACES_DIR,
                    filename
                )

                cv2.imwrite(
                    face_path,
                    face
                )

                balanced_metadata.append({
                    "video_path": row["video_path"],
                    "frame_number": frame_number,
                    "face_path": face_path,
                    "confidence": float(prob),
                    "x1": x1,
                    "y1": y1,
                    "x2": x2,
                    "y2": y2,
                    "face_width": face_width,
                    "face_height": face_height,
                    "label_name": row["label_name"]
                })

        frame_number += 1

    cap.release()


balanced_step4_df = pd.DataFrame(
    balanced_metadata
)

print("=" * 60)
print("BALANCED STEP 4 COMPLETE")
print("=" * 60)

print("Face crops:", len(balanced_step4_df))

print("\nClass distribution:")
print(
    balanced_step4_df["label_name"]
    .value_counts()
)

  0%|          | 0/20 [00:00<?, ?it/s]

Video not found: data/raw\FaceForensics++_C23\original\489.mp4
Video not found: data/raw\FaceForensics++_C23\original\342.mp4
Video not found: data/raw\FaceForensics++_C23\FaceShifter\478_506.mp4
Video not found: data/raw\FaceForensics++_C23\Face2Face\658_627.mp4
Video not found: data/raw\FaceForensics++_C23\original\903.mp4
Video not found: data/raw\FaceForensics++_C23\original\020.mp4
Video not found: data/raw\FaceForensics++_C23\original\555.mp4
============================================================
BALANCED STEP 4 COMPLETE
============================================================
Face crops: 532

Class distribution:
label_name
FAKE    308
REAL    224
Name: count, dtype: int64

In [79]:
print("Face images:", len([
    f for f in os.listdir(BALANCED_FACES_DIR)
    if f.lower().endswith(".jpg")
]))

print("\nMetadata rows:", len(balanced_step4_df))

print("\nLabels:")
print(
    balanced_step4_df["label_name"]
    .value_counts()
)

display(balanced_step4_df.head())

Face images: 532

Metadata rows: 532

Labels:
label_name
FAKE    308
REAL    224
Name: count, dtype: int64

,video_path,frame_number,face_path,confidence,x1,y1,x2,y2,face_width,face_height,label_name
0,data/raw\cel\Celeb-synthesis\id24_id22_0004.mp4,0,/kaggle/working/step4_balanced/faces/video_1_f...,1.000000,233,33,315,140,82,107,FAKE
1,data/raw\cel\Celeb-synthesis\id24_id22_0004.mp4,10,/kaggle/working/step4_balanced/faces/video_1_f...,1.000000,256,34,338,143,82,109,FAKE
2,data/raw\cel\Celeb-synthesis\id24_id22_0004.mp4,20,/kaggle/working/step4_balanced/faces/video_1_f...,1.000000,249,39,329,151,80,112,FAKE
3,data/raw\cel\Celeb-synthesis\id24_id22_0004.mp4,30,/kaggle/working/step4_balanced/faces/video_1_f...,0.999999,255,37,343,152,88,115,FAKE
4,data/raw\cel\Celeb-synthesis\id24_id22_0004.mp4,40,/kaggle/working/step4_balanced/faces/video_1_f...,0.999999,266,39,346,147,80,108,FAKE

In [80]:
tqdm.pandas()

balanced_step4_df["blur_score"] = (
    balanced_step4_df["face_path"]
    .progress_apply(
        calculate_blur_score
    )
)

print("✅ Blur scores calculated")

display(
    balanced_step4_df[
        [
            "face_path",
            "label_name",
            "blur_score"
        ]
    ].head(10)
)

  0%|          | 0/532 [00:00<?, ?it/s]

✅ Blur scores calculated

                                           face_path label_name  blur_score
0  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   50.649740
1  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   44.021214
2  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   36.893645
3  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   57.696971
4  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   43.919856
5  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   37.548318
6  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   40.151820
7  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   47.553037
8  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   42.014065
9  /kaggle/working/step4_balanced/faces/video_1_f...       FAKE   44.136058

In [81]:
print(
    balanced_step4_df["blur_score"].describe()
)

print("\nPercentiles:")

display(
    balanced_step4_df["blur_score"].quantile([
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ])
)

count    532.000000
mean      29.348564
std       17.552704
min       12.752361
25%       20.122341
50%       26.555815
75%       33.622767
max      242.613075
Name: blur_score, dtype: float64

Percentiles:

0.01    13.820570
0.05    15.339630
0.10    16.578948
0.25    20.122341
0.50    26.555815
0.75    33.622767
0.90    43.177358
0.95    50.412319
0.99    61.307690
Name: blur_score, dtype: float64

In [82]:
BLUR_THRESHOLD = 50

print("Blur threshold:", BLUR_THRESHOLD)

Blur threshold: 50

In [83]:
balanced_step4_df["blur_pass"] = (
    balanced_step4_df["blur_score"]
    >= BLUR_THRESHOLD
)

print(
    "Total faces:",
    len(balanced_step4_df)
)

print(
    "Passed blur:",
    balanced_step4_df["blur_pass"].sum()
)

print(
    "Dropped due to blur:",
    (~balanced_step4_df["blur_pass"]).sum()
)

Total faces: 532
Passed blur: 31
Dropped due to blur: 501

In [84]:
print("Face width:")
display(
    balanced_step4_df["face_width"].describe()
)

print("\nFace height:")
display(
    balanced_step4_df["face_height"].describe()
)

Face width:

count    532.000000
mean     127.870301
std       19.590922
min       33.000000
25%      119.000000
50%      128.000000
75%      139.000000
max      178.000000
Name: face_width, dtype: float64

Face height:

count    532.000000
mean     174.759398
std       27.314559
min       41.000000
25%      161.000000
50%      178.000000
75%      190.000000
max      234.000000
Name: face_height, dtype: float64

In [85]:
MIN_FACE_WIDTH = 64
MIN_FACE_HEIGHT = 64

print("Minimum width:", MIN_FACE_WIDTH)
print("Minimum height:", MIN_FACE_HEIGHT)

Minimum width: 64
Minimum height: 64

In [86]:
balanced_step4_df["size_pass"] = (
    (balanced_step4_df["face_width"] >= MIN_FACE_WIDTH) &
    (balanced_step4_df["face_height"] >= MIN_FACE_HEIGHT)
)

print("Passed size:")
print(
    balanced_step4_df["size_pass"].sum()
)

print("\nDropped due to size:")
print(
    (~balanced_step4_df["size_pass"]).sum()
)

Passed size:
529

Dropped due to size:
3

In [88]:
balanced_step4_df["quality_pass"] = (
    balanced_step4_df["blur_pass"] &
    balanced_step4_df["size_pass"]
)

quality_filtered_df = balanced_step4_df[
    balanced_step4_df["quality_pass"]
].copy()

print("=" * 60)
print("QUALITY FILTERING")
print("=" * 60)

print(
    "Faces before:",
    len(balanced_step4_df)
)

print(
    "Faces remaining:",
    len(quality_filtered_df)
)

print(
    "Faces dropped:",
    len(balanced_step4_df)
    - len(quality_filtered_df)
)

============================================================
QUALITY FILTERING
============================================================
Faces before: 532
Faces remaining: 28
Faces dropped: 504

In [89]:
balanced_step4_df["quality_pass"] = (
    balanced_step4_df["blur_pass"] &
    balanced_step4_df["size_pass"]
)

quality_filtered_df = balanced_step4_df[
    balanced_step4_df["quality_pass"]
].copy()

print("=" * 60)
print("QUALITY FILTERING")
print("=" * 60)

print(
    "Faces before:",
    len(balanced_step4_df)
)

print(
    "Faces remaining:",
    len(quality_filtered_df)
)

print(
    "Faces dropped:",
    len(balanced_step4_df)
    - len(quality_filtered_df)
)

============================================================
QUALITY FILTERING
============================================================
Faces before: 532
Faces remaining: 28
Faces dropped: 504

In [90]:
total_in = len(balanced_step4_df)

blur_dropped = (
    ~balanced_step4_df["blur_pass"]
).sum()

size_dropped = (
    balanced_step4_df["blur_pass"] &
    ~balanced_step4_df["size_pass"]
).sum()

remaining = (
    balanced_step4_df["quality_pass"]
).sum()

print("=" * 60)
print("STEP 5 DROP COUNTS")
print("=" * 60)

print("Total input:", total_in)
print("Dropped due to blur:", blur_dropped)
print("Dropped due to size:", size_dropped)
print("Remaining:", remaining)

print(
    "\nTotal dropped:",
    total_in - remaining
)

============================================================
STEP 5 DROP COUNTS
============================================================
Total input: 532
Dropped due to blur: 501
Dropped due to size: 3
Remaining: 28

Total dropped: 504

In [91]:
print("=== BEFORE FILTERING ===")

before_distribution = (
    balanced_step4_df["label_name"]
    .value_counts()
)

display(before_distribution)

print("\n=== AFTER FILTERING ===")

after_distribution = (
    quality_filtered_df["label_name"]
    .value_counts()
)

display(after_distribution)4

SyntaxError: invalid syntax (3902162218.py, line 17)

In [92]:
print("=== BEFORE FILTERING ===")

before_distribution = (
    balanced_step4_df["label_name"]
    .value_counts()
)

display(before_distribution)

print("\n=== AFTER FILTERING ===")

after_distribution = (
    quality_filtered_df["label_name"]
    .value_counts()
)

display(after_distribution)

=== BEFORE FILTERING ===

label_name
FAKE    308
REAL    224
Name: count, dtype: int64

=== AFTER FILTERING ===

label_name
FAKE    18
REAL    10
Name: count, dtype: int64

In [93]:
print("=== BEFORE FILTERING (%) ===")

display(
    balanced_step4_df["label_name"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\n=== AFTER FILTERING (%) ===")

display(
    quality_filtered_df["label_name"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

=== BEFORE FILTERING (%) ===

label_name
FAKE    57.89
REAL    42.11
Name: proportion, dtype: float64

=== AFTER FILTERING (%) ===

label_name
FAKE    64.29
REAL    35.71
Name: proportion, dtype: float64

In [94]:
class_summary = []

for label in ["REAL", "FAKE"]:

    class_df = balanced_step4_df[
        balanced_step4_df["label_name"] == label
    ]

    class_filtered = quality_filtered_df[
        quality_filtered_df["label_name"] == label
    ]

    class_total = len(class_df)
    class_remaining = len(class_filtered)

    class_blur_drop = (
        ~class_df["blur_pass"]
    ).sum()

    class_size_drop = (
        class_df["blur_pass"] &
        ~class_df["size_pass"]
    ).sum()

    class_summary.append({
        "class": label,
        "total_in": class_total,
        "dropped_blur": int(class_blur_drop),
        "dropped_size": int(class_size_drop),
        "remaining": class_remaining,
        "drop_percentage": round(
            (class_total - class_remaining)
            / class_total * 100,
            2
        )
    })

class_summary_df = pd.DataFrame(
    class_summary
)

display(class_summary_df)

  class  total_in  dropped_blur  dropped_size  remaining  drop_percentage
0  REAL       224           211             3         10            95.54
1  FAKE       308           290             0         18            94.16

In [95]:
STEP5_DIR = "/kaggle/working/step5_quality"

os.makedirs(
    STEP5_DIR,
    exist_ok=True
)

FILTERED_PATH = os.path.join(
    STEP5_DIR,
    "quality_filtered_faces.csv"
)

quality_filtered_df.to_csv(
    FILTERED_PATH,
    index=False
)

print("Saved:")
print(FILTERED_PATH)

Saved:
/kaggle/working/step5_quality/quality_filtered_faces.csv

In [96]:
CLASS_SUMMARY_PATH = os.path.join(
    STEP5_DIR,
    "step5_class_summary.csv"
)

class_summary_df.to_csv(
    CLASS_SUMMARY_PATH,
    index=False
)

print("Saved:")
print(CLASS_SUMMARY_PATH)

Saved:
/kaggle/working/step5_quality/step5_class_summary.csv

In [97]:
CLASS_SUMMARY_PATH = os.path.join(
    STEP5_DIR,
    "step5_class_summary.csv"
)

class_summary_df.to_csv(
    CLASS_SUMMARY_PATH,
    index=False
)

print("Saved:")
print(CLASS_SUMMARY_PATH)

Saved:
/kaggle/working/step5_quality/step5_class_summary.csv

In [98]:
print("=" * 60)
print("STEP 5 FINAL CHECK")
print("=" * 60)

print(
    "Filtered CSV exists:",
    os.path.exists(FILTERED_PATH)
)

print(
    "Class summary exists:",
    os.path.exists(CLASS_SUMMARY_PATH)
)

print(
    "Overall summary exists:",
    os.path.exists(OVERALL_SUMMARY_PATH)
)

print("\nFinal face count:")
print(len(quality_filtered_df))

print("\nFinal REAL/FAKE distribution:")
print(
    quality_filtered_df["label_name"]
    .value_counts()
)

============================================================
STEP 5 FINAL CHECK
============================================================
Filtered CSV exists: True
Class summary exists: True

NameError: name 'OVERALL_SUMMARY_PATH' is not defined

In [99]:
import os
import pandas as pd

STEP5_DIR = "/kaggle/working/step5_quality"

os.makedirs(STEP5_DIR, exist_ok=True)

OVERALL_SUMMARY_PATH = os.path.join(
    STEP5_DIR,
    "step5_overall_summary.csv"
)

# Make sure these variables exist
overall_summary = pd.DataFrame([{
    "blur_threshold": BLUR_THRESHOLD,
    "min_face_width": MIN_FACE_WIDTH,
    "min_face_height": MIN_FACE_HEIGHT,
    "total_faces_in": total_in,
    "dropped_blur": int(blur_dropped),
    "dropped_size": int(size_dropped),
    "remaining": int(remaining),
    "total_dropped": int(total_in - remaining),
    "percentage_dropped": round(
        (total_in - remaining) / total_in * 100,
        2
    )
}])

overall_summary.to_csv(
    OVERALL_SUMMARY_PATH,
    index=False
)

print("Overall summary saved:")
print(OVERALL_SUMMARY_PATH)

Overall summary saved:
/kaggle/working/step5_quality/step5_overall_summary.csv

In [100]:
print("=" * 60)
print("STEP 5 FINAL CHECK")
print("=" * 60)

print(
    "Filtered CSV exists:",
    os.path.exists(FILTERED_PATH)
)

print(
    "Class summary exists:",
    os.path.exists(CLASS_SUMMARY_PATH)
)

print(
    "Overall summary exists:",
    os.path.exists(OVERALL_SUMMARY_PATH)
)

print("\nFinal face count:")
print(len(quality_filtered_df))

print("\nFinal REAL/FAKE distribution:")
print(
    quality_filtered_df["label_name"]
    .value_counts()
)print("=" * 60)
print("STEP 5 FINAL CHECK")
print("=" * 60)

print(
    "Filtered CSV exists:",
    os.path.exists(FILTERED_PATH)
)

print(
    "Class summary exists:",
    os.path.exists(CLASS_SUMMARY_PATH)
)

print(
    "Overall summary exists:",
    os.path.exists(OVERALL_SUMMARY_PATH)
)

print("\nFinal face count:")
print(len(quality_filtered_df))

print("\nFinal REAL/FAKE distribution:")
print(
    quality_filtered_df["label_name"]
    .value_counts()
)

SyntaxError: invalid syntax (3939947948.py, line 27)

In [101]:
print("=" * 60)
print("STEP 5 FINAL CHECK")
print("=" * 60)

print(
    "Filtered CSV exists:",
    os.path.exists(FILTERED_PATH)
)

print(
    "Class summary exists:",
    os.path.exists(CLASS_SUMMARY_PATH)
)

print(
    "Overall summary exists:",
    os.path.exists(OVERALL_SUMMARY_PATH)
)

print("\nFinal face count:")
print(len(quality_filtered_df))

print("\nFinal REAL/FAKE distribution:")
print(
    quality_filtered_df["label_name"].value_counts()
)

============================================================
STEP 5 FINAL CHECK
============================================================
Filtered CSV exists: True
Class summary exists: True
Overall summary exists: True

Final face count:
28

Final REAL/FAKE distribution:
label_name
FAKE    18
REAL    10
Name: count, dtype: int64